version: 1
update_configs:
    - package_manager: "java:gradle"
      directory: "./app/"
      update_schedule: "daily"
      commit_message:
          prefix: "chore(deps)"

    - package_manager: "java:gradle"
      directory: "./maps-ktx/"
      update_schedule: "daily"
      commit_message:
          prefix: "chore(deps)"

    - package_manager: "java:gradle"
      directory: "./maps-utils-ktx/"
      update_schedule: "daily"
      commit_message:
          prefix: "chore(deps)"
